speechSynthesis.cancel();var isSpeaking=!1;let audioBlob;var speech=new SpeechSynthesisUtterance();speech.rate=1;speech.pitch=1;speech.volume=1;speech.voice=speechSynthesis.getVoices()[0];function speakInputText(){isSpeaking=!0;speech.text=document.getElementById("textInput").value;speechSynthesis.speak(speech)}
function pauseSpeech(){if(isSpeaking){isSpeaking=!1;speechSynthesis.pause();document.getElementById("pauseButton").innerHTML=`resume`}else{isSpeaking=!0;speechSynthesis.resume();document.getElementById("pauseButton").innerHTML=`pause` }}
function stopSpeech(){isSpeaking=!1;speechSynthesis.cancel()}
function changeVoice(voice){if(voice=="voice1"){speech.voice=speechSynthesis.getVoices()[8]}else if(voice=="voice2"){speech.voice=speechSynthesis.getVoices()[0]}else if(voice=="voice3"){speech.voice=speechSynthesis.getVoices()[1]}else if(voice=="voice4"){speech.voice=speechSynthesis.getVoices()[11]}else if(voice=="voice5"){speech.voice=speechSynthesis.getVoices()[12]}else if(voice=="voice6"){speech.voice=speechSynthesis.getVoices()[18]}else if(voice=="voice7"){speech.voice=speechSynthesis.getVoices()[33]}else if(voice=="voice8"){speech.voice=speechSynthesis.getVoices()[37]}else if(voice=="voice9"){speech.voice=speechSynthesis.getVoices()[41]}}
function changeVoiceSpeed(voiceSpeed){if(voiceSpeed=="speed2"){speech.rate=2}else if(voiceSpeed=="speed1.75"){speech.rate=1.75}else if(voiceSpeed=="speed1.5"){speech.rate=1.5}else if(voiceSpeed=="speed1.25"){speech.rate=1.25}else if(voiceSpeed=="speed1"){speech.rate=1}else if(voiceSpeed=="speed0.75"){speech.rate=0.75}else if(voiceSpeed=="speed0.5"){speech.rate=0.5}}
let mediaRecorder;let recordedChunks=[];const startButton=document.getElementById('startButton');const stopButton=document.getElementById('stopButton');const playButton=document.getElementById('playButton');const audioElement=document.getElementById('audioElement');const plusButton=document.getElementById('plusButton');const reload=document.getElementById('reset');startButton.addEventListener('click',startRecording);stopButton.addEventListener('click',stopRecording);playButton.addEventListener('click',playRecording);plusButton.addEventListener('click',()=>{startRecording();speakInputText();stopButton();speakInputText()})
function startRecording(){navigator.mediaDevices.getUserMedia({audio:!0}).then(function(stream){mediaRecorder=new MediaRecorder(stream);mediaRecorder.ondataavailable=function(event){recordedChunks.push(event.data)};mediaRecorder.onstop=function(){const blob=new Blob(recordedChunks,{type:'audio/mp3'});const url=URL.createObjectURL(blob);audioElement.src=url;playButton.disabled=!1;audioElement.controls=!0};startButton.disabled=!0;startButton.innerHTML="recording...";startButton.style.color = 'white';
startButton.style.backgroundColor='blue';stopButton.disabled=!1;stopButton.style.backgroundColor='red';stopButton.style.color='white';stopButton.classList.remove('disabled');recordedChunks=[];mediaRecorder.start()}).catch(function(err){console.error('Error accessing microphone:',err)}); speakInputText();}
function stopRecording(){if(mediaRecorder&&mediaRecorder.state!=='inactive'){mediaRecorder.stop();startButton.disabled=!1;startButton.classList.remove('disabled');startButton.style.color="white";stopButton.disabled=!0;stopButton.style.opacity=0.3;startButton.innerHTML="start Recording";startButton.style.opacity=0.4;playButton.innerHTML="Play Now";playButton.style.backgroundColor='green';playButton.style.color="white"}}
function playRecording(){stopButton.disabled=!0;stopButton.classList.add('disabled');audioElement.play()}
if(startButton.disabled = true){
stopButton.style.backgroundColor = "red";
}